version: "3.8"

services:
  thermopolia_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redisdata:/data

volumes: 
  pgdata:
  redisdata: